

export const connectionConstants={

    /**
     * 加载连接列表
     */
    LOAD_CONNECTION_LIST :'LOAD_CONNECTION_LIST',

    EXPAND_STATE:'EXPAND_STATE',

    /**
     * 更新
     */
    UPDATE_STATE:'UPDATE_CONNECTION_STATE',

   
    DELETE_CONNECTION:'DELETE_CONNECTION',

    ADD_CONNECTION:'ADD_CONNECTION',

    MODIFY_CONNECTION:'MODIFY_CONNECTION',

}