export const contextMenuIds={

   
     CONNECTION_CONTEXTMENU_ID : 'CONNECTION_CONNECT_CONTEXTMENU_ID',

     DB_CONTEXTMENU_ID : 'DB_CONTEXTMENU_ID',

     KEY_CONTEXTMENU_ID:'KEY_CONTEXTMENU_ID',
 

     
}