

export const keyConstants={

    LOAD_KEY_LIST :'LOAD_KEY_LIST',

    SELECT_KEY:'SELECT_KEY',

    SET_KEY_SAVE_HANDLE:'SET_KEY_SAVE_HANDLE',
   
    SET_KEY_DIRTY_STATE:'SET_KEY_DIRTY_STATE',

    SET_KEY_NONE_STATE:'SET_KEY_NONE_STATE',

}